# Generated by Django 4.1.7 on 2023-03-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ia_app', '0002_empresa_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.URLField(null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ia_app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('id_navegador', models.BigIntegerField(null=True)),
                ('bot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ia_app.bot')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='tema',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='ia_app.tema'),
        ),
    ]
