# Generated by Django 4.1.7 on 2023-04-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ia_app', '0004_rename_tema_id_bot_tema_rename_bot_id_mensajes_bot_and_more'),
    ]

    operations = [
        
    ]
