# Generated by Django 4.1.7 on 2023-04-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ia_app', '0005_rename_tema_id_bot_tema_alter_bot_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boton',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.BooleanField()),
                ('colorBot', models.TextField()),
                ('colorUsr', models.TextField()),
                ('background', models.BooleanField()),
                ('colorPrimary', models.TextField()),
                ('colorSecondary', models.TextField()),
                ('typeColor', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ia_app.bot')),
            ],
        ),
    ]
